DROP TABLE PR_USERINFO;
DROP SEQUENCE PR_MEMBERSQ;

--멤버 번호, 아이디, 비밀번호, 이름, 주소, 전화번호,
--이메일, 가입여부(가입 Y/탈퇴 N), 등급(ADMIN, USER,...)

CREATE SEQUENCE PR_MEMBERSQ;

CREATE TABLE PR_USERINFO(
PR_NO NUMBER NOT NULL,
PR_ID VARCHAR2(500) UNIQUE,
PR_PW VARCHAR2(500) NOT NULL,
PR_NAME VARCHAR2(1000) NOT NULL,
PR_ADDR VARCHAR2(2000) NOT NULL,
PR_PHONE VARCHAR2(20) NOT NULL,
PR_EMAIL VARCHAR2(100) NOT NULL,
PR_ENABLED VARCHAR2(2) NOT NULL,
PR_ROLE VARCHAR2(20) NOT NULL,
CONSTRAINT PR_USERINFO_PK PRIMARY KEY (PR_NO),
CONSTRAINT PR_USERINFO_ENABLED_CHK CHECK (PR_ENABLED IN ('y', 'n'))
);

INSERT INTO PR_USERINFO VALUES (PR_MEMBERSQ.NEXTVAL, 'ADMIN', '1234', '관리자', '관리시 관리구', '010-0000-0000', 'ADMIN@MYMEMBER.COM', 'y', 'ADMIN');
INSERT INTO PR_USERINFO VALUES (PR_MEMBERSQ.NEXTVAL, 'user', '1234', 'userTest', 'userTest 테스트구', '010-0000-0000', 'USER@MYMEMBER.COM', 'y', 'ADMIN');
INSERT INTO PR_USERINFO VALUES (PR_MEMBERSQ.NEXTVAL, 'aaa', '1234', 'userTest', 'userTest 테스트구', '010-1234-0000', 'aaa@MYMEMBER.COM', 'y', 'ADMIN');
INSERT INTO PR_USERINFO VALUES (PR_MEMBERSQ.NEXTVAL, 'sss', '1234', 'userTest', 'userTest 테스트구', '010-1234-0000', 'sss@naver.com', 'y', 'USER');
INSERT INTO PR_USERINFO VALUES (PR_MEMBERSQ.NEXTVAL, 'hahaha', '1234', 'userTest', 'userTest 테스트구', '010-1234-0000', 'sss@naver.com', 'y', 'USER');

UPDATE PR_USERINFO SET PR_ENABLED = 'y';
DELETE FROM PR_USERINFO;

SELECT * FROM PR_USERINFO;
